# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendlabel = QtWidgets.QLabel(self.centralwidget)
        self.sendlabel.setGeometry(QtCore.QRect(30, 95, 150, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.sendlabel.setFont(font)
        self.sendlabel.setObjectName("sendlabel")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 100, 420, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.closebutton = QtWidgets.QPushButton(self.centralwidget)
        self.closebutton.setGeometry(QtCore.QRect(640, 315, 100, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.closebutton.setFont(font)
        self.closebutton.setObjectName("closebutton")
        self.chooseIDbox = QtWidgets.QComboBox(self.centralwidget)
        self.chooseIDbox.setGeometry(QtCore.QRect(190, 20, 150, 30))
        self.chooseIDbox.setObjectName("chooseIDbox")
        self.chooseIDbox.addItem("")
        self.chooseIDbox.addItem("")
        self.chooseIDbox.addItem("")
        self.showtext = QtWidgets.QTextBrowser(self.centralwidget)
        self.showtext.setGeometry(QtCore.QRect(30, 145, 580, 200))
        self.showtext.setObjectName("showtext")
        self.portlabel = QtWidgets.QLabel(self.centralwidget)
        self.portlabel.setGeometry(QtCore.QRect(370, 55, 150, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.portlabel.setFont(font)
        self.portlabel.setObjectName("portlabel")
        self.clientIDlabel = QtWidgets.QLabel(self.centralwidget)
        self.clientIDlabel.setGeometry(QtCore.QRect(30, 15, 150, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.clientIDlabel.setFont(font)
        self.clientIDlabel.setObjectName("clientIDlabel")
        self.switcherIPtext = QtWidgets.QTextBrowser(self.centralwidget)
        self.switcherIPtext.setGeometry(QtCore.QRect(190, 60, 150, 30))
        self.switcherIPtext.setObjectName("switcherIPtext")
        self.switcherIPlabel = QtWidgets.QLabel(self.centralwidget)
        self.switcherIPlabel.setGeometry(QtCore.QRect(30, 55, 150, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.switcherIPlabel.setFont(font)
        self.switcherIPlabel.setObjectName("switcherIPlabel")
        self.sendbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sendbutton.setGeometry(QtCore.QRect(640, 100, 100, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.sendbutton.setFont(font)
        self.sendbutton.setObjectName("sendbutton")
        self.porttext = QtWidgets.QTextBrowser(self.centralwidget)
        self.porttext.setGeometry(QtCore.QRect(440, 60, 170, 30))
        self.porttext.setObjectName("porttext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.sendlabel.setBuddy(self.lineEdit)
        self.portlabel.setBuddy(self.porttext)
        self.clientIDlabel.setBuddy(self.chooseIDbox)
        self.switcherIPlabel.setBuddy(self.switcherIPtext)

        self.retranslateUi(MainWindow)
        self.sendbutton.clicked.connect(self.sendandrcvmessage) # type: ignore
        self.closebutton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "client"))
        self.sendlabel.setText(_translate("MainWindow", "发送内容"))
        self.closebutton.setText(_translate("MainWindow", "关闭"))
        self.switcherIPtext.setText(_translate("MainWindow", "127.0.0.1"))
        self.porttext.setText(_translate("MainWindow", "10000"))
        self.chooseIDbox.setItemText(0, _translate("MainWindow", "A"))
        self.chooseIDbox.setItemText(1, _translate("MainWindow", "B"))
        self.chooseIDbox.setItemText(2, _translate("MainWindow", "C"))
        self.portlabel.setText(_translate("MainWindow", "端口号"))
        self.clientIDlabel.setText(_translate("MainWindow", "本进程标识"))
        self.switcherIPlabel.setText(_translate("MainWindow", "交换机：IP地址"))
        self.sendbutton.setText(_translate("MainWindow", "发送"))