# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'switcherui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showtext = QtWidgets.QTextBrowser(self.centralwidget)
        self.showtext.setGeometry(QtCore.QRect(30, 80, 651, 271))
        self.showtext.setObjectName("showtext")
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.NATIP = QtWidgets.QTextBrowser(self.centralwidget)
        self.NATIP.setFont(font)
        self.NATIP.setGeometry(QtCore.QRect(170, 20, 181, 41))
        self.NATIP.setObjectName("NATIP")
        self.PORT = QtWidgets.QTextBrowser(self.centralwidget)
        self.PORT.setFont(font)
        self.PORT.setGeometry(QtCore.QRect(500, 20, 181, 41))
        self.PORT.setObjectName("PORT")
        self.natiplabel = QtWidgets.QLabel(self.centralwidget)
        self.natiplabel.setGeometry(QtCore.QRect(40, 30, 131, 21))
        self.natiplabel.setFont(font)
        self.natiplabel.setObjectName("natiplabel")
        self.natportlabel = QtWidgets.QLabel(self.centralwidget)
        self.natportlabel.setGeometry(QtCore.QRect(420, 30, 71, 21))
        self.natportlabel.setFont(font)
        self.natportlabel.setObjectName("natportlabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 360, 211, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.closeButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.natiplabel.setBuddy(self.NATIP)
        self.natportlabel.setBuddy(self.PORT)

        self.retranslateUi(MainWindow)
        self.closeButton.clicked.connect(MainWindow.close) # type: ignore
        self.startButton.clicked.connect(MainWindow.start) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "switcher"))
        self.natiplabel.setText(_translate("MainWindow", "NAT网关：IP"))
        self.natportlabel.setText(_translate("MainWindow", "端口号"))
        self.startButton.setText(_translate("MainWindow", "start"))
        self.closeButton.setText(_translate("MainWindow", "close"))
        self.NATIP.setText(_translate("MainWindow", "127.0.0.1"))
        self.PORT.setText(_translate("MainWindow", "10001"))
