# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'routerui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 609)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showtext = QtWidgets.QTextBrowser(self.centralwidget)
        self.showtext.setGeometry(QtCore.QRect(20, 340, 831, 251))
        self.showtext.setObjectName("showtext")
        self.serverip = QtWidgets.QTextBrowser(self.centralwidget)
        self.serverip.setFont(font)
        self.serverip.setGeometry(QtCore.QRect(130, 30, 161, 41))
        self.serverip.setObjectName("serverip")
        self.serverport = QtWidgets.QTextBrowser(self.centralwidget)
        self.serverport.setFont(font)
        self.serverport.setGeometry(QtCore.QRect(420, 30, 161, 41))
        self.serverport.setObjectName("serverport")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(610, 30, 93, 28))

        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(730, 30, 93, 28))

        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.serveriplabel = QtWidgets.QLabel(self.centralwidget)
        self.serveriplabel.setGeometry(QtCore.QRect(40, 40, 81, 21))

        self.serveriplabel.setFont(font)
        self.serveriplabel.setObjectName("serveriplabel")
        self.serverportlabel = QtWidgets.QLabel(self.centralwidget)
        self.serverportlabel.setGeometry(QtCore.QRect(300, 40, 121, 21))

        self.serverportlabel.setFont(font)
        self.serverportlabel.setObjectName("serverportlabel")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(20, 90, 831, 241))
        self.table.setRowCount(0)
        self.table.setColumnCount(6)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(0, 0, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.serveriplabel.setBuddy(self.serverip)
        self.serverportlabel.setBuddy(self.serverport)

        self.retranslateUi(MainWindow)
        self.startButton.clicked.connect(MainWindow.start) # type: ignore
        self.closeButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "router"))
        self.startButton.setText(_translate("MainWindow", "start"))
        self.closeButton.setText(_translate("MainWindow", "close"))
        self.serveriplabel.setText(_translate("MainWindow", "服务器IP"))
        self.serverportlabel.setText(_translate("MainWindow", "服务器端口"))
        self.serverip.setText(_translate("MainWindow", "127.0.0.1"))
        self.serverport.setText(_translate("MainWindow", "10002"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "协议"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "内网IP"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "内网端口"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "公网IP"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "公网端口"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "剩余时间"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        self.table.setSortingEnabled(__sortingEnabled)
